/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorColumn(length = 31)
public abstract class Anexo extends Arquivo {

}