/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.*;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
public class Documento extends Arquivo {

    @Basic
    private String procedencia;

    @ManyToOne(fetch = FetchType.LAZY)
    private TipoDocumento tipoDocumento;

    @ManyToOne(fetch = FetchType.LAZY)
    private Processo processo;

    @ManyToOne(fetch = FetchType.LAZY)
    private Usuario criador;

    @Version
    private long revisao;

    public String getProcedencia() {
        return this.procedencia;
    }

    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }

    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    public Processo getProcesso() {
        return this.processo;
    }

    public void setProcesso(Processo processo) {
        this.processo = processo;
    }

    public Usuario getCriador() {
        return this.criador;
    }

    public void setCriador(Usuario criador) {
        this.criador = criador;
    }

    public long getRevisao() {
        return this.revisao;
    }

    public void setRevisao(long revisao) {
        this.revisao = revisao;
    }

}