/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import java.util.Optional;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;
import javax.ws.rs.FormParam;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorColumn(length = 31, name = "DTYPE")
public abstract class Pessoa extends BaseEntity {

    @Basic
    @FormParam("nome")
    @NotNull
    private String nome;

    @Basic
    @FormParam("email")
    @Email
    private String email;

    @Basic
    @FormParam("telefone")
    private String telefone;

    public Optional<String> getNome() {
        return Optional.ofNullable(this.nome);
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

}