/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.Basic;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.ws.rs.FormParam;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorValue("REPRESENTANTE")
public class Representante extends Pessoa {

    @Basic
    @FormParam("cargo")
    private String cargo;

    public String getCargo() {
        return this.cargo;
    }

    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

}