/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorValue("DOCUMENTO")
public class TipoDocumento extends Tipo {

}