/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorValue("PROCESSO")
public class TramiteProcesso extends Tramite {

    @ManyToOne(fetch = FetchType.LAZY)
    private Processo processo;

    public Processo getProcesso() {
        return this.processo;
    }

    public void setProcesso(Processo processo) {
        this.processo = processo;
    }

}