/**
 * This file was generated by the Jeddict
 */
package br.com.imerljak.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;

/**
 * @author Israel Merljak <imerljak@gmail.com.br>
 */
@Entity
@DiscriminatorValue("DENUNCIA")
public class TramiteDenuncia extends Tramite {

    @ManyToOne(fetch = FetchType.LAZY)
    private Denuncia denuncia;

    public Denuncia getDenuncia() {
        return this.denuncia;
    }

    public void setDenuncia(Denuncia denuncia) {
        this.denuncia = denuncia;
    }

}